---
- name: installing wildfly(JBOSS)
  become: yes
  hosts: all
  tasks:
    - name: installing java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Download foo.conf
      ansible.builtin.get_url:
        url: https://github.com/wildfly/wildfly/releases/download/25.0.1.Final/wildfly-25.0.1.Final.tar.gz
        dest: /etc/wildfly-25.0.1.Final.tar.gz
        mode: "0777"
    - name: Create Folder
      ansible.builtin.file:
        path: /opt/wildfly
        mode: "0777"
        state: directory
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /etc/wildfly-25.0.1.Final.tar.gz
        dest: /opt/wildfly
        remote_src: yes
    - name: Ensure group "somegroup" exists
      ansible.builtin.group:
        name: wildfly
        state: present
    - name: Add the user 'tinku' with a specific uid and a primary group of 'wildfly'
      ansible.builtin.user:
        name: tinku
        comment: wildfly user
        uid: 8873
        group: wildfly
    - name: Create Folder
      ansible.builtin.file:
        path: /etc/wildfly
        mode: 0777
        state: directory
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/wildfly
        owner: tinku
        group: wildfly
        mode: '0777'
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/wildfly/wildfly-25.0.1.Final/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        owner: tinku
        group: wildfly
        mode: '0777'
        remote_src: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/wildfly/wildfly-25.0.1.Final/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        owner: tinku
        group: wildfly
        mode: '0777'
        remote_src: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /opt/wildfly/wildfly-25.0.1.Final/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        owner: tinku
        group: wildfly
        mode: '0777'
        remote_src: yes
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /opt/wildfly/bin/launch.sh
        owner: tinku
        group: wildfly
        mode: '0777'
    - name: ensure the apache service is running and enabled
      ansible.builtin.systemd:
        name: wildfly.service
        state: restarted
        daemon_reload: yes
    - name: Start a service with systemd
      systemd:
        name: wildfly.service
        state: started
    - name: Enable nginx service
      systemd:
        name: wildfly.service
        enabled: true
        masked: no